name: Atualizador GEX
on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Isso reforça a permissão de escrita diretamente no código
    steps:
      - uses: actions/checkout@v4 # Versão atualizada

      - name: Setup Python
        uses: actions/setup-python@v5 # Versão atualizada
        with:
          python-version: '3.11'

      - name: Rodar Script
        run: python update_gex.py

      - name: Commit e Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Niveis Atualizados via Bot" || echo "Sem mudanças para salvar"
          git push
